### ISSUE TITLE
Matrixformule resulteert niet in cellen gevuld als een matrix

### ISSUE THREAD

**Issue by GoofPluto** [bwelman/leerexcel#1]
Goedendag,

nav uw pagina https://leerexcel.netlify.app/08-arrays.html probeer ik matrixformules onder de knie te krijgen.
Echter als ik in een cel in Excel {1\2\3\4} invoer, dan verschijnt alleen 1 in de cel, maar de 2, 3 en 4 worden niet zichtbaar. Zowel niet als ik dit invoer met een 'kale' Enter of met CTRL+SHIFT+ENTER.
De Excel die ik gebruik is MS Office 2019 Thuisgebruik en Zelfstandigen.

Wat doe ik niet goed? Hoe krijg ik die matrices wel werkend in Excel?
Alvast dank voor uw reactie
agg@planet.nl

**Comment by bwelman** [comment]
Voor zover ik weet werkt de nieuwe manier om matrixformules in te voeren (dus zonder ctrl+shift+enter) alleen in Excel 365 en Excel 2021 en niet in Excel 2019 en ouder. Helaas beschik ik niet over Excel 2019, waardoor ik niet kan testen of dit klopt.  Voor Excel 2019 en ouder moet je de methode met ctrl+shift+ enter gebruiken. Er staat me bij dat je dan het hele uitvoergebied moet selecteren.
Probeer het volgende eens uit in een nieuw leeg werkblad. Selecteer de cellen A1 t/m D1, typ als formule in ={1\2\3\4} en druk dan op ctrl+shift+enter. Wanneer dit ook niet werkt, voeg dan bij jouw reactie ook het excelbestand bij zodat ik daar eens naar kan kijken.

**Comment by GoofPluto** [comment]
Goedendag,
 
Inderdaad met Excel 2019 is het eerst de reeks selecteren en dan de formule invoeren met CTRL+SHIFT+Enter. Bedankt voor de tip
Groeten
GoofPluto
